// Code generated by Slice Machine. DO NOT EDIT.

import About from './About/index.svelte';
import Bento from './Bento/index.svelte';
import ExpertiseCards from './ExpertiseCards/index.svelte';
import Hero from './Hero/index.svelte';
import TechList from './TechList/index.svelte';

export const components = {
	about: About,
	bento: Bento,
	expertise_cards: ExpertiseCards,
	hero: Hero,
	tech_list: TechList
};
