// Code generated by Slice Machine. DO NOT EDIT.

import About from './About/index.svelte';
import Hero from './Hero/index.svelte';
import TechList from './TechList/index.svelte';

export const components = {
	about: About,
	hero: Hero,
	tech_list: TechList
};
